repos:
-   repo: https://github.com/psf/black
    rev: 23.10.0
    hooks:
    - id: black
      language_version: python3
      exclude: ^alembic/

- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    exclude: ^alembic/
    additional_dependencies:
      - flake8-docstrings
      - flake8-string-format
    args: [
      "--extend-ignore=D100,D101,D102,D103,D104,D105,D107",  # docstring ignore
      "--extend-ignore=E501,W503",  # long strings and line break before binary operator
    ]

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        exclude: ^alembic/
