version: '3.8'
services:
  app:
    build: .
    container_name: chat-bot-app
    ports:
      - "8000:8000"
    volumes:
      - .:/chat_bot
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - chat-bot-network

  db:
    hostname: db
    image: ankane/pgvector
    ports:
     - 5432:5432
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chat-bot-network

volumes:
  postgres_data:


networks:
  chat-bot-network:
    driver: bridge
